server:
  port: 9527
spring:
  application:
    name: wuai-gateway
  cloud:
    gateway:        #Gateway支持yml编码。当路由数量过于庞大,也可以在代码中配置。
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名称进行路由。
      routes:
        - id: payment_routh   #payment_route #路由的ID没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001    #匹配后提供服务的路由地址#
          uri: lb://PAYORDER-SERVER #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/payment/create/**      #断言,路径相匹配的进行路由
        - id: payment_routh2
          #uri: http://localhost:8001
          uri: lb://PAYORDER-SERVER #匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/payment/query/**
        - id: payment_routh3
          #uri: http://localhost:8001
          uri: https://news.baidu.com/ #匹配后提供服务的路由地址
          predicates:
            - Path=/user/login/**
    nacos:
      discovery:
        server-addr: localhost:8848


#eureka:
#  instance:
#    hostname: cloud-gateway-service
#  client:
#    register-with-eureka: false  	# 不在注册中心注册
#    fetch-registry: true 			# 需要从注册中心拉取服务
#    service-url:        # 注册中心的地址
#      defaultZone: http://localhost:7001/eureka/
